### ISSUE TITLE
Homebridge plugin?

### ISSUE THREAD

**Issue by gigafonzie** [ptz0n/node-verisure#1]
Hey,

Have you thought about packaging this up as a homebridge plugin...would be super awesome.

Or perhaps you have some instructions for how to get it working as is? I'd be happy to help test it for you

Im looking for a way to trigger the lights on and off when the alarm state changes.

Ben

**Comment by elbogi** [comment]
Would be very interested in the same as well.

**Comment by elbogi** [comment]
It's been [made](https://github.com/ptz0n/node-verisure) and it's working like a charm 👍

**Comment by ptz0n** [comment]
As @elbogi mentioned above, it's done 🌡

https://github.com/ptz0n/homebridge-verisure
