### ISSUE TITLE
Calling twice gives error from verisure

### ISSUE THREAD

**Issue by ksvan** [ptz0n/node-verisure#13]
Making a node-red wrapper on top of this. Works first time around, when calling the second time to fetch status i get the error below:

"<response><status><errorGroup>UNAUTHORIZED</errorGroup><errorCode>AUT_00041</errorCode><errorMessage>Cannot use both basic authentication and cookie authentication.</errorMessage></status></response>"

**Comment by ptz0n** [comment]
Hi I thanks for posting this issue. Can you please share some example code?

**Comment by ksvan** [comment]
Yes. My first node-red package, so might be something related to how its executed in that context. Pushed it, a bit early, for providing sample code. https://github.com/ksvan/node-red-contrib-verisure/tree/master/verisurenode

**Comment by ksvan** [comment]
Did make a work-around now, just cant reuse the Verisure object/connection. Need to make a new for every node-red on-input event on node.

**Comment by ptz0n** [comment]
Sorry, but I don't see why you can't reuse the instance, token & installation. Just put them in a scope above or before your logic that handles input messages.

Depending on how often you need to handle input messages, I'm afraid that Verisure might rate limit your auth requests.
