### ISSUE TITLE
Change status on device?

### ISSUE THREAD

**Issue by ludvigaldrin** [ptz0n/node-verisure#37]
Not really an issue with your code but more about me :)
Im playing around with your code and have gotten the example working. Now I want to change lock/unlock a door. But don't really get how to update a device status. Probably just me being a noob at this but would really glad if you could post a sample of doing a change to an item. 

Thanks for your help

**Comment by ptz0n** [comment]
Hi Ludvig & thanks for reaching out.

For examples of how to update device states, please have a look at https://github.com/ptz0n/homebridge-verisure
