### ISSUE TITLE
Get Overview? Change Armstate in version 5

### ISSUE THREAD

**Issue by ludvigaldrin** [ptz0n/node-verisure#53]
Hi!
Love your work man. It has been running solid for a long time. Now I want to try the version 5 out. 
Im struggling thou to understand how to get it working. 

Your example is about broadband but if I would like to say:

1. Get Alarm State (previous found under getOverview on installation
2. Put new state to the Alarm

How can that be done?
Thanks for your help

**Comment by ptz0n** [comment]
Hi Ludvig and thanks for reaching out.

Here's an example operation for getting the arm state:

```javascript
{
  operationName: 'ArmState',
  query: `query ArmState($giid: String!) {
    installation(giid: $giid) {
      armState {
        type
        statusType
        date
        name
        changedVia
        __typename
      }
    }
  }`,
}
```

An overview equivalent operation can be found here: https://github.com/ptz0n/homebridge-verisure/blob/07a8dbdaafef7c29de28c4e216e7773d778bc396/lib/operations.js#L2-L88

**Comment by ludvigaldrin** [comment]
Perfect worked like a charm just what I needed. My node is now up and running again.
